owncloud/ocis-php-sdk

README.md

no need to mention my private ocis instance here :-)

don't mention private ocis instance in the docs

---

README.md
composer.json
src/Drive.php
src/DriveOrder.php
src/DriveType.php
src/Exception/BadRequestException.php
src/Exception/ExceptionHelper.php
src/Exception/ForbiddenException.php
src/Exception/NotFoundException.php
src/Exception/UnauthorizedException.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/OrderDirection.php
src/ResourceMetadata.php
src/WebDavClient.php
tests/unit/Owncloud/OcisSdkPhp/DriveOrderTest.php
tests/unit/Owncloud/OcisSdkPhp/DriveTypeTest.php
tests/unit/Owncloud/OcisSdkPhp/OcisTest.php
tests/unit/Owncloud/OcisSdkPhp/OrderDirectionTest.php
tests/unit/Owncloud/OcisSdkPhp/ResourceTest.php
tests/unit/Owncloud/OcisSdkPhp/WebDavClientTest.php

I ran all the tests locally:
```
make test-php-style
make test-php-phan
make test-php-phpstan
make test-php-unit
```
and they all pass.

Rename to OcisPhpSdk to match repo name

---

src/Drive.php
src/Ocis.php
src/WebDavClient.php

This PR refactors `webDavRequest` function name  to `sendRequest` and replaced the request function with `sendRequest`

Rename webdavRequest function 

---

src/Drive.php

This PR adds empty trashbin method

Implement empty trashbin

---

.drone.star

running codestyle, phan, php-stan and unit tests on CI
related issue: https://github.com/owncloud/ocis-php-sdk/issues/3

adding .drone.star file to run unit and other tests on ci

---

src/Drive.php
src/Exception/ExceptionHelper.php
src/Exception/HttpException.php
src/Exception/InvalidResponseException.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/WebDavClient.php
tests/unit/Owncloud/OcisSdkPhp/OcisTest.php
tests/unit/Owncloud/OcisSdkPhp/ResourceTest.php
tests/unit/Owncloud/OcisSdkPhp/WebDavClientTest.php

1. document in more details which exceptions are thrown
2. throw better exceptions in some cases

improve exception handling & documentation

---

.drone.star
.gitignore
README.md
phpdoc.dist.xml
src/Drive.php
src/DriveOrder.php
src/DriveType.php
src/Exception/BadRequestException.php
src/Exception/ExceptionHelper.php
src/Exception/ForbiddenException.php
src/Exception/HttpException.php
src/Exception/InvalidResponseException.php
src/Exception/NotFoundException.php
src/Exception/UnauthorizedException.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/OrderDirection.php
src/ResourceMetadata.php
src/WebDavClient.php
tests/unit/Owncloud/OcisSdkPhp/ResourceTest.php

1. improve documentation of classes and functions
2. improve exception messages
3. generate docs using phpdoc.org/
4. publish docs to https://owncloud.dev/ocis-php-sdk/

improve and publish documentation

---

.drone.star
Makefile
phpunit.xml
sonar-project.properties

Enable sonar cloud analysis
I believe the coverage information we will be able to see after merging to main

test coverage

---

src/Drive.php
src/Ocis.php

define strings that are used over and over again in seperate costs
fixes #30

don't repeat messages, define them in const

---

src/Exception/ExceptionHelper.php

turn the logic of the if statements around: if we can get anything usefull from the response body of the `ApiException` then use it, in any other case use the existing exception message as the new message
fixes #29

reduce complexity of getHttpErrorException

---

src/Exception/ExceptionHelper.php

by that we also reduce the amount of return statements to one
fixes #33

change switch to match statement

---

src/Drive.php

fixes sonar cloud issue: https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&resolved=false&id=owncloud_ocis-php-sdk&open=AYsY7u62wCB8P94PULz2

split long line

---

src/Ocis.php
tests/unit/Owncloud/OcisPhpSdk/OcisTest.php

I hope this will make sonarcloud think that the function is now easier to understand.
I had to define all the parameters into single variables and declare the details of the array to make phpstan happy
fixes #31

reduce complexity of getNotifications

---

src/Drive.php
src/Exception/NotImplementedException.php

throw custom exception for not yet implemented functions to make sonar cloud happy
fixes #32

use dedicated NotImplementedException

---

src/Ocis.php

an other try to reduce complexity by removing if staments and putting them into a loop
because I use a new variable and don't reuse `$ocsData` phpstan does not complain this time
hopefully fixes #31

reduce complexity by removing if statements

---

.drone.env
.drone.star
.gitignore
Makefile
tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
tests/integration/docker/keycloak/ocis-ci-realm.dist.json
tests/integration/docker/keycloak/ocis-realm.dist.json

This PR adds integration test in CI
- https://github.com/owncloud/ocis-php-sdk/issues/16

Add integration test in CI

---

src/OcisResource.php

just some minor improvement on documentation of `OcisResource`

improve documentation of OcisResource

---

.drone.star
.gitignore
composer.json
composer.lock

This PR cache php dependencies
https://github.com/owncloud/ocis-php-sdk/issues/53

Cache dependencies

---

.drone.star

The `tests` function and the `phpunit` function in the drone script are very similar, so lets combine them

merge phpunit function into tests function

---

.drone.star

Cache ocis

---

composer.json
src/Group.php
src/Ocis.php
src/SharingRole.php
src/User.php

some changes needed to use the new generator

move to libregraph generated with php-nextgen

---

.drone.env
src/Ocis.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

implementing create group
fixes : https://github.com/owncloud/ocis-php-sdk/issues/63
better to merge [this](https://github.com/owncloud/ocis-php-sdk/pull/66) first so the CI passes

adding create groups

---

README.md

These names were changed in #72, but not adjusted in the README

fix function names in README

---

src/Group.php
src/Ocis.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php

implementing adding user to group

implementing adding user to group

---

src/Ocis.php

This PR get share by me api request method

Get share by me resources

---

src/Ocis.php
src/ShareRecieved.php

Added getShareWithMe Resource list

Get share with me resources

---

src/Group.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

This PR implements user removal form Group. 
Related issues: https://github.com/owncloud/ocis-php-sdk/issues/93

remove user from group function implementation

---

src/ShareReceived.php

these functions are irrelevant for now
fixes #92

delete accept & decline functions

---

src/Drive.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php

enable the drive, the trick here is to send the header
fixes #109

function to enable a drive

---

tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

on top of #115
test delete drive

test deleting drive

---

tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

Add test coverage for getting drive info

Extend get drive tests coverage

---

README.md

correct version of ocis

---

.drone.env
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/UsersTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php

related issue: https://github.com/owncloud/ocis-php-sdk/issues/120

bumping ocis commit id

---

src/Ocis.php
src/User.php
tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/UsersTest.php
tests/unit/Owncloud/OcisPhpSdk/UserTest.php

tests for listing groups and users as a normal user

adding test for listing users and groups by normal user

---

src/Drive.php
src/Exception/ExceptionHelper.php
src/Exception/InternalServerErrorException.php
src/Group.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/Share.php
src/ShareCreated.php
src/ShareLink.php
src/WebDavClient.php
tests/unit/Owncloud/OcisPhpSdk/Exception/ExceptionHelperTest.php

so that clients can catch it seperately

create a specific exception for 500 errors

---

tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php

This add tests for move and upload

Add test for move 

---

src/Ocis.php
src/Share.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php

This PR add step to return sharelink object created by the user.
Related Issue:https://github.com/owncloud/ocis-php-sdk/issues/113

modified getSharedbyMe function

---

tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

these places were forgotten in #135

remove remaining dashes from group names

---

src/Ocis.php

get the definition up-to-date and eliminate a long line

update connectionConfig definition

---

src/Share.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

this PR adds tests for setting expiration date to a share

adding test for setting expiration date of a share

---

.drone.env

run tests with current master of ocis, to see if https://github.com/owncloud/ocis/issues/8068 was fixed

bump ocis for tests

---

src/Ocis.php
tests/integration/Owncloud/OcisPhpSdk/NotificationTest.php

This PR adds tests for notification

Add tests for notification

---

tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareReceivedTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeTest.php
tests/integration/Owncloud/OcisPhpSdk/UsersTest.php

This PR addresses to this issue . https://github.com/owncloud/ocis-php-sdk/issues/104

getOcis function implemented in all step

---

tests/integration/Owncloud/OcisPhpSdk/NotificationTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareReceivedTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeTest.php

Related to https://github.com/owncloud/ocis-php-sdk/issues/171

moved repeated function for getting personal drive to OcisPhpSdkTestCase folder

---

tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

Related issue:https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated for DriveTest

---

tests/integration/Owncloud/OcisPhpSdk/NotificationTest.php

Related issue:https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion for Notification updated

---

src/ShareCreated.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

Add tests for update Share Permission like password role and expiration

Add more tests coverage for shares

---

tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php

Related issue : https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion for GetResourceTest updated

---

tests/integration/Owncloud/OcisPhpSdk/ShareReceivedTest.php

Related issues: https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated for ShareReceivedTest

---

tests/integration/Owncloud/OcisPhpSdk/UsersTest.php

Related issue: https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion for UsersTest  updated

---

.drone.star

IDE says that this variable is not needed

delete not needed variable

---

tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php

Related issue: https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated in GetSharedByMe Test

---

tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

Related issue : https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated for ShareCreatedModifyTest

---

.drone.star
sonar-project.properties

This PR fixes test coverage report
Fixes: https://github.com/owncloud/ocis-php-sdk/issues/181

updated coverage report

---

.drone.star

Refactor some variable names to maintain the standard as mentioned in this comment https://github.com/owncloud/ocis-php-sdk/pull/174#pullrequestreview-1812701028

Update variable name

---

tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

Related issue: https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated for OcisTest

---

tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php

Related issue : https://github.com/owncloud/ocis-php-sdk/issues/131

error message in assertion updated for resource share test

---

.drone.star

this PR adds starlark linter pipeline in ci
related issue: https://github.com/owncloud/ocis-php-sdk/issues/196

adding starlark linter in ci

---

.drone.star
tests/get-latest-ocis-commit-id.sh

Run sdk with the lastest commit id in nightly
Ocis-php-sdk fail with latest ocis commitId while sending invite to group. 
Work on progress to fix that bug on this https://github.com/owncloud/ocis-php-sdk/pull/203

Run nightly

---

.drone.star

This PR fix trigger for ocis cache pipeline and cache dependencies for release

fix trigger for nightly and release

---

tests/unit/Owncloud/OcisPhpSdk/DriveOrderTest.php
tests/unit/Owncloud/OcisPhpSdk/DriveTypeTest.php
tests/unit/Owncloud/OcisPhpSdk/Exception/ExceptionHelperTest.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php
tests/unit/Owncloud/OcisPhpSdk/OcisTest.php
tests/unit/Owncloud/OcisPhpSdk/OcisWebfingerTest.php
tests/unit/Owncloud/OcisPhpSdk/OrderDirectionTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php
tests/unit/Owncloud/OcisPhpSdk/UserTest.php

similar to what was done for the integration tests in PR #210

chore(tests): tidy unit tests

---

composer.json
src/Drive.php

This Pr update libre graph package which supports ocis 6.0.0

Update libre graph package

---

tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

This PR adds test cases for sharing drive to user and group and checking resources and getMyshares. 
Part of https://github.com/owncloud/ocis-php-sdk/issues/223
Tests added
- testDriveInviteToGroup
- testGetDriveShareResourceByReceiver
- testGetMyDriveForDriveShareReceiver

added tests for sharing drive to user and group

---

tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php

refactoring ShareGetShareByMeTest.php file

---

tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeNotSyncedSharesTest.php

refactoring ShareTestGetSharedWithMeNotSyncedSharesTest.php file

---

tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

refactoring ShareCreatedModifyTest.php file

---

tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php

refactoring ResourceShareLinkTest.php file

---

tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php

refactoring GroupsTest.php file

---

README.md

This PR adds drive invitation-related part on the readme

Add drive invitation on readme

---

src/Exception/TooEarlyException.php
src/Ocis.php

Nightly was failing because of the new phan update so adjusting the code to new specifications

fixing phan error

---

src/BaseUser.php
src/EducationUser.php
src/Ocis.php
tests/unit/Owncloud/OcisPhpSdk/EducationUserTest.php

This PR implements listing of an education user
https://owncloud.dev/libre-graph-api/#/educationUser/ListEducationUsers
https://owncloud.dev/libre-graph-api/#/educationUser/GetEducationUser

implementing listing education user

---

src/EducationUser.php
src/Ocis.php

This PR add method to delete education user

Add delete education user

---

tests/integration/Owncloud/OcisPhpSdk/UsersTest.php

This PR add integration tests coveragae for getUserByID
-  testGetAUserUsingID
- testGetAUserUsingInvalidUserID

Add tests coverage for get user by id

---

README.md

This PR adds documentation for using education endpoint
related issue: https://github.com/owncloud/ocis-php-sdk/issues/260

adding documentation for using education endpoint
