owncloud/ocis-php-sdk

src/DriveOrder.php
src/DriveType.php
src/Ocis.php
src/OrderDirection.php
tests/unit/Owncloud/OcisSdkPhp/DriveOrderTest.php
tests/unit/Owncloud/OcisSdkPhp/DriveTypeTest.php
tests/unit/Owncloud/OcisSdkPhp/OrderDirectionTest.php

We already use `enum` for https://github.com/owncloud/ocis-php-sdk/blob/main/src/ResourceMetadata.php
Refactor to use `enum` for DriveOrder DriveType OrderDirection
This prevents the possibility of anyone passing an invalid value. If they do, PHP itself will complain straight away, we do not have to write code to check.
I looked at `README.md` and I don't think that the examples there need any changes. Methods like `listMyDrives` still take parameters specified like `DriveOrder::NAME` `OrderDirection::ASC` `DriveType::PERSONAL` - they are now `enum`s but they are specified the same way as when they were public constants.

Use enum for DriveOrder DriveType OrderDirection

---

src/Drive.php

Maybe it will be nicer if drive->getType() returns a DriveType object (an instance of the DriveType enum) and throws an exception if and invalid drive type happens. That will allow the consumer to always work with the DriveType enum object, rather than potentially processing strings that happen to be the "known values" like "personal" "project" etc.

return DriveType object from drive->getType()

---

Makefile
phpunit.xml
src/Drive.php
src/Ocis.php
tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
tests/integration/compose.yaml
tests/integration/docker/keycloak/Dockerfile

basic framework and first small set of integration tests
`make test-php-integration` should make it run locally
1. ocis is started with keycloak and some well known users
2. tokens are fetched using oidc flow type `Resource Owner Password Flow` setting `grant_type=password`
3. tokens are used to do various operations through the SDK

basic framework to run integration tests

---

.phan/config.php
src/Drive.php
src/Notification.php
src/Ocis.php
src/WebDavClient.php
tests/unit/Owncloud/OcisSdkPhp/OcisTest.php
tests/unit/Owncloud/OcisSdkPhp/OcisWebfingerTest.php
tests/unit/Owncloud/OcisSdkPhp/WebDavClientTest.php

In more complex setups the service Url might not be known at the beginning but the webfinger service needs to be asked.
As the SDK expects a token to be present it only does authenticated requests to webfinger.
In this PR I'm introducing a new parameter to `$connectionConfig` to switch on the webfinger discovery.
so the object creation would be:
`$ocis = new Ocis($webfinger_url, $access_token->token, ['webfinger' => true]);`
The SDK then contacts the webfinger service, finds the first link with `"rel": "http://webfinger.owncloud/rel/server-instance"` and uses that as the service URL to do Graph & WebDAV requests.
The corresponding PR for moodle: https://github.com/owncloud/moodle-repository_ocis/pull/5
For the unit tests I've refactored the `$connectionConfig`, so that it can also take a …

use webfinger

---

.drone.star

CI is only partly running on merges.
example:
This should fix that by unifying all the triggers. There have been 2 mistakes with the triggers:
1. `"refs/head/main"` should be `"refs/heads/main"`
2. there is no master branch, so `"refs/heads/master"` should be `"refs/heads/main"`

fix triggers for CI

---

Makefile
README.md
tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
tests/integration/compose.yaml
tests/integration/docker/keycloak/Dockerfile
tests/integration/docker/keycloak/ocis-realm.dist.json

1. use `ocis.owncloud.test` and `keycloak.owncloud.test` instead of ocis.sdk.test
2. don't use `host-gateway` to avoid firewall issues
3. add healthchecks for every service
4. start depending service only when the healthcheck of the previous passed, to make sure the tests are not executed too early
5. show more log messages for ocis
6. added instructions how to run integration tests into the README

improve integration tests docker

---

src/Drive.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/WebDavClient.php
tests/unit/Owncloud/OcisSdkPhp/OcisTest.php
tests/unit/Owncloud/OcisSdkPhp/OcisWebfingerTest.php
tests/unit/Owncloud/OcisSdkPhp/ResourceTest.php
tests/unit/Owncloud/OcisSdkPhp/WebDavClientTest.php

Sonarcloud allows only 120char per line, what is a sensible maximum, so this PR splits the lines that are too long.
fixes #28

reduce length of lines to permitted 120char

---

.gitignore

to avoid accidentally committing things like `clover.xml` that can be generated locally when running unit tests.

Ignore files in /tests/output/

---

Makefile

Fixes #36 
I purposely ran a set of integration tests without ocis properly set up, so that they failed. This was the result:
```
ERRORS!
Tests: 5, Assertions: 0, Errors: 5.
Generating code coverage report in Clover XML format ... done [00:00.234]
make[1]: Entering directory '/home/phil/git/owncloud/ocis-php-sdk'
cd tests/integration && docker compose down -v --remove-orphans
[+] Running 7/7
✔ Container integration-keycloak-1  Removed                                                                                        0.4s 
✔ Container integration-traefik-1   Removed                                                                                        0.0s 
✔ Container integration-ocis-1      Removed …
```

Always run docker-clean after integration tests

---

src/Ocis.php

with this check we don't need to write an `if` statement for every key, but can just give the check in the value of `$validConnectionConfigKeys`
this should also fix the sonar issue with too many return statements, see https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&resolved=false&id=owncloud_ocis-php-sdk&open=AYsY7u6LwCB8P94PULzk
fixes #35

check the connection config dynamically

---

tests/unit/Owncloud/OcisPhpSdk/Exception/ExceptionHelperTest.php

It didn't turn out to be too difficult to test `ExceptionHelper` at unit test level.
I have made test cases for all the 4 possible input exception classes `GuzzleException|ApiException|SabreClientHttpException|SabreClientException`
with each of the interesting status codes that might happen.
That verifies that the appropriate custom exception is returned for each combination of inputs.

Add unit tests for getHttpErrorException

---

src/Notification.php
src/Ocis.php

this makes sonar cloud happy, see https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&resolved=false&id=owncloud_ocis-php-sdk&open=AYsY7u7CwCB8P94PUL0R&tab=code
but I'm not sure if we should do that, feels like having less control over the types

reduce amount of parameters

---

.drone.star
sonar-project.properties

with this PR we
1. run the integration tests with PHP 8.1 and 8.2
2. collect the coverage data from the integration tests and make sonar analyze it
current coverage shows 61% and after this PR its estimated to be 71.2%, so sonarcloud did pick up the changes
fixes #17

get coverage of integration tests

---

src/Ocis.php
tests/integration/Owncloud/OcisSdkPhp/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisSdkPhp/OcisTest.php
tests/integration/Owncloud/OcisSdkPhp/UsersTest.php

To do sharing, we first need user objects to share with. We don't want the programmer to have to initiate users, so they need to come from ocis.
This PR implements a function to get users from oCIS

function to get/search users

---

tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/UsersTest.php

1. the folder was called "OcisSdkPhp", but should be "OcisPhpSdk"
2. the main class for the testscase had a typo "Std" should be "Sdk"

fix typos in integration tests

---

tests/check-oCIS-cache.sh

This PR adds a script to check if ocis cache already exist in a bucket or not.

add script to check ocis cache

---

.drone.star
composer.lock
docs-hugo-header.md

the `include` functionality for hugo somehow did not work, see https://github.com/owncloud/ocis-php-sdk/commits/docs-hugo
so maybe we can just copy the content of the readme and the header directly into the `_index.md`
fixes #52

compile and upload hugo docs for https://owncloud.dev/clients/ocis-php-sdk/

---

README.md
src/Drive.php
src/Ocis.php
src/OcisResource.php
src/SharingRole.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

Implementing sharing of resources.
Sharing (invite) can happen on any resource.
Before the invite we need recipients (groups or users) and a role. The possible roles are retrieved from the item `"@libre.graph.permissions.roles.allowedValues"` in [/v1beta1/drives/{drive-id}/items/{item-id}/permissions](https://owncloud.dev/libre-graph-api/#/drives.permissions/ListPermissions)

implementing sharing functionality

---

composer.json

This PR just uses a valid license name `Apache-2.0`

Use valid licence name

---

src/Drive.php
src/OcisResource.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

in these API calls we actually need the `driveId` not the `itemId` as the first argument see https://owncloud.dev/libre-graph-api/#/drives.permissions/Invite
So forwarding the driveId from the drive class down to the resource and using it there

use driveId instead or itemId as first argument in API calls

---

src/Drive.php
src/OcisResource.php
src/ResourceMetadata.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

Functionality to get the private link for a resource.
The link is delivered using the WebDAV properties, see https://owncloud.dev/apis/http/webdav/#listing-properties
I don't believe this is a very expensive data to generate, so I've decided to get it directly with the main request, alternatively we could send a new request just when calling `getPrivatelink`, but I don't think its worth it.

get private link

---

composer.json
src/OcisResource.php
src/Share.php
src/ShareCreated.php
src/ShareLink.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php

1. `invite()` function returns an array of `ShareCreated` objects
2. `ShareCreated` & `ShareLink` extend the `Share` class, which combines functions/properties that are needed in both places
3. the role in `ShareCreated` can be changed (and of course anything that is extended from `Share`)

allow a share to be updated

---

phpdoc.dist.xml
src/Group.php
src/OcisResource.php
src/Share.php
src/ShareLink.php
src/SharingRole.php
src/User.php

1. ignore some constructors in the docs, because a developer using this library should never use them
2. add/fix path to classes from the dependency that we want to see in the docs

Improve autogenerated documentation

---

src/Ocis.php
src/OcisResource.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

- If only a file-id is known, allow the user to create an `OcisResource` just using that. The use-case is that an application might have stored the file-id in the database and then wants to use all the abilities of `OcisResource` with it.
- move the functions to get the content of a file to the `OcisResource` class. Does that make sense? We can also keep both, but the naming might be confusing.

create OcisResource object from file-id

---

composer.json
src/Share.php

after the fix in the [libre-graph-api](https://github.com/owncloud/libre-graph-api/pull/145) we can now delete the expiration date

allow removal of expiration date of shares

---

src/Ocis.php
src/OcisResource.php
src/ShareReceived.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

and other minor typos - silly English.
This will break any consumer that uses `ShareReceived` directly.

fix: spelling of ShareReceived class

---

src/Drive.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

When listing drives (spaces) it might be handy to know if a particular drive is currently disabled to be able to display it differently or not at all.

ability to check if drive is disabled

---

src/Ocis.php
tests/unit/Owncloud/OcisPhpSdk/OcisTest.php

This PR unify the dependency injector used for unit testing and remove the setter function and use configuration array to mock different drive config.
Related issue:https://github.com/owncloud/ocis-php-sdk/issues/83

dependency injector made consistent

---

src/Ocis.php
src/Share.php
src/ShareCreated.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php

If one got a `ShareCreated` object its handy to be able to find out who the receiver of the share is. For a share just created it might not be so useful as the receiver is known, but when finding shares by `SharedByMe` its useful.

get receiver of share

---

tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php

Since many tests related to group were added in OcisTest inside our integration test, this PR focus on rearranging the test code and make them seperate file.

rearranged group related integration tests

---

.drone.env
.drone.star
composer.json
src/OcisResource.php
src/Share.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php

This PR adds test to set the expiration date during creation of shares and links.
The tests revealed some issues that have been fixed:
- makes all date variables immutable, so that the passed in objects are not changed
- delete the timezone conversion, its not needed
- set the link type as object and not string

tests to set expiration date when creating shares and links

---

src/Ocis.php
src/WebDavClient.php

allow to set proxy settings to force all connections over the proxy.
How to test:
1. install mitmproxy.org
2. set proxy settings, which are the same format like in guzzle: https://docs.guzzlephp.org/en/stable/request-options.html#proxy
3. check if all expected requests go through mitmproxy

support proxy settings

---

composer.json
src/Drive.php
src/Exception/ConflictException.php
src/Exception/ExceptionHelper.php
src/Exception/TooEarlyException.php
src/Ocis.php
src/OcisResource.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/compose.yaml
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

The main purpose of this PR is to create upload tests, but to make them (basically the downloads) reliably I had to implement catching 425(too early) issues.
This is based on https://github.com/sabre-io/dav/pull/1519
should fix #75

upload tests & catch 425 responses

---

tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php

unskip the test, because the related bug in ocis was fixed

unskip test for share link with past expiry

---

.drone.env
src/Drive.php
src/Ocis.php
src/OcisResource.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/integration/compose.yaml
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php

with https://github.com/owncloud/ocis/pull/7975 we don't need to try to get the 'real' drive-id from the server, we can directly use the `spaceid` from the PROPFIND response as drive-id in the graph API.
Fixes: https://github.com/owncloud/moodle-repository_ocis/issues/49

use spaceid from PROPFIND in OcisResource

---

tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

currently in ocis we can't search for groups if the search query contains '-'. so its better not create groups with that character in our tests

removing '-' from group names

---

src/OcisResource.php
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php

fixes #138
oCIS will allow a maximum of one invite at a time after https://github.com/owncloud/ocis/pull/8019
We can make the change here already now

restrict invite requests to a single receiver

---

.drone.env

Use the newest ocis to run the intergration tests.

bump ocis for tests to the newest version

---

tests/integration/Owncloud/OcisPhpSdk/UsersTest.php

these lines will never be reached, because the exception is thrown before that

delete unused lines

---

src/ShareReceived.php
tests/integration/Owncloud/OcisPhpSdk/ShareReceivedTest.php

refactoring:
- make names consistent
- return `DateTimeImmutable` as we do in other places

test getters of ShareReceived and refactor where needed

---

src/WebDavClient.php
tests/unit/Owncloud/OcisPhpSdk/WebDavClientTest.php

put the logic into seperate functions to reduce the brain overload
should fix this sonarcloud issue: https://sonarcloud.io/project/issues?resolved=false&id=owncloud_ocis-php-sdk&open=AYxJNLpIXSLLZfMn53jn
Tested also locally with moodle proxy settings

refactor logic out of createCurlSettings into sub functions

---

tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

this PR adds tests for deleting share link
and removes unused variable in `testSetExpirationDateOnObjectFromInvite` function

adding test for deleting a share link

---

.drone.star

corrected version of #150
the docs pipeline might have run before the cache of the dependencies was build and by that installed the wrong dependencies
fixes #149

make docs pipeline depend on cache-dependency pipeline

---

.drone.star
.gitignore
Makefile
composer.json
phpunit.xml
tests/integration/Owncloud/OcisPhpSdk/OcisResourceTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceShareLinkTest.php
tests/unit/Owncloud/OcisPhpSdk/DriveOrderTest.php
tests/unit/Owncloud/OcisPhpSdk/DriveTypeTest.php
tests/unit/Owncloud/OcisPhpSdk/Exception/ExceptionHelperTest.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php
tests/unit/Owncloud/OcisPhpSdk/OcisTest.php
tests/unit/Owncloud/OcisPhpSdk/OcisWebfingerTest.php
tests/unit/Owncloud/OcisPhpSdk/OrderDirectionTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceTest.php
tests/unit/Owncloud/OcisPhpSdk/UserTest.php
tests/unit/Owncloud/OcisPhpSdk/WebDavClientTest.php

PHPunit major version 10 requires PHP 8.1 and later. This project also requires PHPunit 8.1 or later. So we can use the latest PHPunit `10.5.*` release for testing.
Passes for me locally - it needs `php-xdebug` in CI.
I added drone starlark code to install `php8.n-xdebug` in the pipelines that run `phpunit`. And adjusted the command for running unit tests so that it has "coverage" mode enabled for the PHP xdebug extension. That gets things working in CI and locally.

test: use phpunit 10.5

---

src/Drive.php
src/Group.php
src/Notification.php
src/Ocis.php
src/OcisResource.php
src/Share.php
src/ShareLink.php
src/WebDavClient.php
tests/unit/Owncloud/OcisPhpSdk/WebDavClientTest.php

Declare a `phpstan-type` called `ConnectionConfig` to be the long declaration of what a connection config array can contain.
Use that in the places where we have various long declarations of the array-shape of a connection config.
In some places, the array-shape currently just declared a minimal set of things that were relevant to the method (for example, `getCurlHeaders` in `WebDavClient.php` only mentioned the "headers" array key). But we can happily pass a whole connection config array, and the method `getCurlHeaders` takes it, and only happens to deal with the "headers" key.
So I think it is OK (and good) to declare that all these methods take any `ConnectionConfig` as an input parameter.
PBPstan documentation for this feature is at …

Refactor phpstan doc for ConnectionConfig

---

tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeTest.php

This PR adds the integration test for getSharedWithMe function

added testGetsharewithme

---

src/User.php
tests/unit/Owncloud/OcisPhpSdk/UserTest.php

previously we validated the response from server in constructor in user class but now this PR moves that logic to the getters.

refactoring user class to validate data from server inside getters

---

src/User.php
tests/unit/Owncloud/OcisPhpSdk/UserTest.php

We have been using the PHP `empty` function in a few places for validation.
That is dangerous because things like the ASCII string "0" are considered "empty". And there can be unusual edge cases where "0" is a valid string value. For example, someone could set their display name to the ASCII string "0".
This PR replaces 2 uses of `empty` with more specific validation.
We should look for other uses of `empty` and inspect them and replace with more specific checks.

fix: allow id or display name to be '0'

---

phpunit.xml
src/Ocis.php

phpunit 10 was reporting:
```
php -d memory_limit=4096M -d zend.enable_gc=0 -d xdebug.mode=coverage "vendor/bin/phpunit" --configuration ./phpunit.xml --testsuite unit
PHPUnit 10.5.5 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.3.0 with Xdebug 3.3.0alpha2
Configuration: /home/phil/git/owncloud/ocis-php-sdk/phpunit.xml
.......................................D.DDDDDDDDDDDDDD........  63 / 157 ( 40%)
............DDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDD.................. 126 / 157 ( 80%)
...............................                                 157 / 157 (100%)
Time: 00:00.871, Memory: 18.00 MB
OK, but there were issues!
Tests: 157, Assertions: 337, Deprecations: 2.
Generating code coverage report in Clover XML format ... done [00:00.021]
```
Lots of unit test cases are …

fix: deprecations reported by phpunit

---

.drone.star

1) name unit test pipelines correctly
2) name integration test steps correctly
I noticed these when trying to add PHP 8.3 to CI. We may as well fix this now.

Adjust drone script

---

.drone.star

https://drone.owncloud.com/owncloud/ocis-php-sdk/880/9/3
`Error response from daemon: manifest for owncloudci/php:8.3 not found: manifest unknown: manifest unknown`
I will make a PR upstream to generate an `owncloudci/php:8.3` - done in PR https://github.com/owncloud-ci/php/pull/169
Passes now - please review.

ci: run tests with PHP 8.3

---

src/Group.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php

previously we validated the response from server in constructor in group class but now this PR moves that logic to the getters.

refactoring group class to validate data from server inside getters

---

src/ShareLink.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php

previously we validated the response from server in constructor in `ShareLink` class but now this PR moves that logic to the getters.

refactoring sharelink class to validate data from server inside getters

---

src/Share.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php

previously we validated the response from server in constructor in share class but now this PR moves that logic to the getters.

refactoring share class to validate data from server inside getters

---

src/SharingRole.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetShareByMeTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceInviteTest.php

previously we validated the response from server in constructor in sharing role class but now this PR moves that logic to the getters.

refactoring sharing role class to validate data from server inside getters

---

.drone.star
tests/check-oCIS-cache.sh

This PR changes the scripting file to check one commit ID once.
Checking both master and ocis commit id in the bash file makes it non-reusable for dynamic case.
In addition to that on CI,  `cache-ocis-master` and `cache-ocis-stable` run same bash script.

Fix ocis cache check script

---

tests/integration/Owncloud/OcisPhpSdk/ShareGetSharedWithMeTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeNotSyncedSharesTest.php

Related issue : https://github.com/owncloud/ocis-php-sdk/issues/131
The foldername `ShareTestGetSharedWithMeTest` is changed to `ShareGetSharedWithMeTest` for coherent name as all our file is named in similar style.

error message and filename updated for ShareGetSharedWithMeTest

---

src/Exception/ExceptionHelper.php
src/Ocis.php

Issue #200 
If API calls return an OdataError object, then find the error code and message in the object, and use it to create and throw the appropriate HTTP error exception, like other code does. So consumers of the SDK can get a consistent type of exception when something goes wrong.

fix: improve handling of OdataError

---

src/ShareReceived.php
tests/integration/Owncloud/OcisPhpSdk/OcisPhpSdkTestCase.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetSharedWithMeTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareTestGetSharedWithMeNotSyncedSharesTest.php

fix the spelling so that it is consistent with `getAtClientSynchronize` and other places where we spell Synchronize.
This will effect anything that uses this public method. I suppose that we will need to change any calls from the Moodle integration.
~And maybe it should be called `isClientSynchronized` to read more nicely?~ (done)

fix: rename isClientSynchronize method

---

src/Ocis.php
tests/unit/Owncloud/OcisPhpSdk/OcisWebfingerTest.php

The token is not decoded using `base64` but `base64Url` see https://jwt.io/introduction/
`base64Url` uses `-` and `_` instead of `+` and `/`, see https://datatracker.ietf.org/doc/html/rfc4648#section-5
This PR is on top of #207, so review only last commit and merge after #207
fixes #208

decode token using Base64Url

---

tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareCreatedModifyTest.php

This PR updates the test which were related to a fixed issue in ocis
related issue: https://github.com/owncloud/ocis-php-sdk/issues/192

updated skipped test

---

src/ShareLink.php

fix: getDisplayName cannot return null

---

src/Drive.php

fixes #220 
I declared `object $image` because that is the closest that we know is likely, and it keeps `phpstan` happy that a type is declared.

fix: do not explicitly declare GdImage

---

src/Group.php
tests/unit/Owncloud/OcisPhpSdk/GroupTest.php

function `setMembers` only had one line of code which was used in only one place so refactoring `setMembers` function in `Group.php` and unit tests related to it.

refactoring setmembers function in group.php and unit tests related to it

---

.drone.star
src/Drive.php
src/Ocis.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

This PR adds function which gets permission list of drives using root endpoint 
- added tests coverage for getRole()
Part of issue #223

Add support for get roles of drive using root endpoint

---

src/DriveShare.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

This PR adds support for set roles and set Expiration date 
https://github.com/owncloud/ocis-php-sdk/issues/223

Add support for update drive share

---

tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

Tests added:
- testReceiverInviteOtherUserToDriveShare
- testReceiverInviteOtherUserToDriveShareWithNoInvitePermission
- testReceiverUpdatesDriveShareRole
- testReceiverUpdatesDriveShareRoleNoEnoughPermission
Part of https://github.com/owncloud/ocis-php-sdk/issues/223

tests for updating drive share role and inviting another user

---

.phan/config.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php

- use the `PHPUnitAssertionPlugin` for phan. That makes phan understand that after PHPunit assert methods, like `assertInstanceOf`, that the variable now has to be of the asserted type. That makes the phan analysis better match the test code.
- replace a lot of "if (some variable is empty) then throw an exception" with `assertInstanceOf` PHPunit checks
- remove a lot of try/catch blocks that are not needed. We were catching an unexpected `EndPointNotImplementedException` exception and then calling `$this->fail`. But if an unexpected exception happens, PHPunit will fail the test anyway, and report the exception that happened.
I think that this simplifies the code flow of a lot of the test cases. Please review.
If people agree, then it can be done for other test code.

Refactor DriveTest to simplify it

---

.php-cs-fixer.dist.php
src/BaseUser.php
src/Drive.php
src/Group.php
src/Ocis.php
tests/integration/Owncloud/OcisPhpSdk/DriveTest.php
tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php
tests/integration/Owncloud/OcisPhpSdk/OcisTest.php
tests/integration/Owncloud/OcisPhpSdk/ResourceInviteTest.php
tests/integration/Owncloud/OcisPhpSdk/ShareGetSharedWithMeTest.php
tests/unit/Owncloud/OcisPhpSdk/ResourceLinkTest.php

When reviewing PRs I notice that we sometimes write:
`if(`
`foreach(`
and sometimes:
`if (`
`foreach (`
PSR-12 does not enforce if there must be a space before the opening `(` or not. But we should be consistent.
In other repos we always have a single space before the `(`
Add the optional php-cs-fixer rule https://cs.symfony.com/doc/rules/language_construct/single_space_around_construct.html

chore: enforce php-cs-fixer single_space_around_construct

---

src/Ocis.php

Currently phan has been failing due to 
```
+ make test-php-phpstan
vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress src tests
------ ----------------------------------------------- 
Line   src/Ocis.php                                   
------ ----------------------------------------------- 
334    Offset 0 does not exist on array{0?: string}.  
------ ----------------------------------------------- 
```
This PR fix it

fix phan error

---

src/Group.php
tests/integration/Owncloud/OcisPhpSdk/GroupsTest.php

This PR add function rename under Group class and add test coverage too.
Part of 
- https://github.com/owncloud/ocis-php-sdk/issues/256

Add support for group rename

---

src/Ocis.php
tests/unit/Owncloud/OcisPhpSdk/OcisTest.php

The access token is made optional because the education user can work without that token and has its own education access token. 
`setEducationGuzzleClient` is removed because the setter is not necessary for the SDK.  It can be set from outside by giving them in `educationAccessToken`
The new implementation is done in a way that if both token isn't provided, the error will be thrown in object creation.
Each function that uses accesstoken is checked on their own function body.

access token optional function added

---

src/Ocis.php

There is only one identity object held in this variable.
See comment https://github.com/owncloud/ocis-php-sdk/pull/263/files#r1764598622

Use singular "identity" for variable name

---

phpdoc.dist.xml

previously phpstan variable were shown in the documentation 
before:
now this pr ignores those phpstan variable when generating the docs
after:

ignoring phpstan info from documentation

---

docs-hugo-header.md

maybe that is the reason the docs on https://owncloud.dev/ocis-php-sdk don't get updated

Update date in docs-hugo-header.md

---

src/Ocis.php

this constant values do not need to show up in the docs and specially I want to test if updating the docs on https://owncloud.dev/ocis-php-sdk/ works again correctly

ignore internal const in documentation

---

.gitattributes

When installing ocis-php-sdk, all folders and files are included, resulting in a large package size that may inconvenience users. To address this, a .gitattributes file is added to exclude unnecessary files and folders, keeping the installation lightweight.

Exclude unnecessary files during composer installation.
